build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

filter:
    excluded_paths:
        - 'l10n/*'
        - 'tests/'
        - 'vendor/*'

imports:
    - php

