name: Build
on: pull_request
jobs:
  build-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16, 18 ]
    name: Build front-end with Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
    env:
      CI: true

  summary:
    runs-on: ubuntu-latest
    needs:
      - build-js
    if: always()
    name: Build summary
    steps:
      - name: Static analysis status
        run: if ${{ needs.build-js.result != 'success' && needs.build-js.result != 'skipped' }}; then exit 1; fi
