name: Dependabot auto approve

on:
  pull_request_target:
    branches:
      - main
      - master
      - stable*

jobs:
  dependabot-approve:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          target: minor
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          use-github-auto-merge: true
