name: Dependabot auto approve

on:
  pull_request_target:
    branches:
      - main
      - master
      - stable*

jobs:
  dependabot-approve:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
