name: Dependabot auto approve

on:
  pull_request_target:
    branches:
      - main
      - master
      - stable*

jobs:
  dependabot-approve:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: "${{ secrets.GITHUB_TOKEN }}"
