name: Static analysis
on: pull_request

permissions:
  contents: read

jobs:
  static-psalm-analysis:
      runs-on: ubuntu-latest
      strategy:
          matrix:
              ocp-version: [ 'dev-master', 'dev-stable31', 'dev-stable30' ]
      name: Nextcloud ${{ matrix.ocp-version }}
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up php
            uses: shivammathur/setup-php@v2
            with:
                php-version: 8.1
                coverage: none
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Install dependencies
            run: composer i
          - name: Install OCP package
            run: composer require --dev nextcloud/ocp:${{ matrix.ocp-version }} -W
          - name: Run coding standards check
            run: composer run psalm

  summary:
    runs-on: ubuntu-latest
    needs:
      - static-psalm-analysis
    if: always()
    name: static-analysis-summary
    steps:
      - name: Static analysis status
        run: if ${{ needs.static-psalm-analysis.result != 'success' && needs.static-psalm-analysis.result != 'skipped' }}; then exit 1; fi
